#server port
server:
  port: 8080
#jsp
#prefix, suffix
#databasepool
spring:
  -mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  -datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
 
    
#mybatis 위치 잡아주기
#mapper 위치 잡아주기
mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: user.bean
  mapper-locations: classpath:mapper/**/*.xml


